### POST SHEET
POST http://{{host}}:{{port}}/api/v1/sheet
Content-Type: application/json

{
  "name" : "rain drop",
  "author" : "iu",
  "creatorEmail" : "s2mos2@naver.com"
}

### GET SHEET
GET http://{{host}}:{{port}}/api/v1/sheet/2

### GET SHEET LIST
GET http://{{host}}:{{port}}/api/v1/sheet?page=0&size=10

### GET SHEET DETAIL
GET http://{{host}}:{{port}}/api/v1/sheet/detail/2

### QUERY ALL SHEET
POST http://{{host}}:{{port}}/api/v1/sheet/query?page=0&size=10
Content-Type: application/json

{
  "conditions" : [
    {
      "target" : "name",
      "values" : ["별보러", "가자"],
      "queryOption" : "like"
    }
  ],
  "conditionOption" : "or"
}

### PUT SHEET
PUT http://{{host}}:{{port}}/api/v1/sheet/2
Content-Type: application/json

{
  "name" : "it is up to you",
  "author" : "yunhwadngdng",
  "creatorEmail" : "hello@google.com"
}

### DELETE SHEET
DELETE http://{{host}}:{{port}}/api/v1/sheet/2

### POST BAR
POST http://{{host}}:{{port}}/api/v1/bar
Content-Type: application/json

{
  "no" : "",
  "lyrics" : "",
  "fingeringId" : "1",
  "sheetId" : "6"
}

### POST BAR LIST BY EL
POST http://{{host}}:{{port}}/api/v1/bar/el
Content-Type: application/json

{
  "barEl" : "|<>Heart beats fast Colors and promises How to be brave How can I love when I'm afraid to fall Watching you stand alone All of my doubt suddenly goes away somehow One step closer [Chorus] I have died everyday waiting for you Darling don't be afraid I have loved you For a thousand years I'll love you for a thousand more Time stands still Beauty in all she is I will be brave I will not let anything take away Standing in front of me Every breath Every hour has come to this One step closer [Chorus] I have died everyday waiting for you Darling don't be afraid I have loved you For a thousand years I'll love you for a thousand more And all along I believed I would find you Time has brought your heart to me I have loved you for a thousand years I'll love you for a thousand more One step closer One step closer [Chorus] I have died everyday waiting for you Darling don't be afraid I have loved you For a thousand years I'll love you for a thousand more And all al"
}

### GET BAR
GET http://{{host}}:{{port}}/api/v1/bar/2

### GET BAR LIST
GET http://{{host}}:{{port}}/api/v1/bar?page=0&size=10

### QUERY ALL BAR
POST http://{{host}}:{{port}}/api/v1/bar/query?page=0&size=10
Content-Type: application/json

{
  "conditions" : [
    {
      "target" : "sheetId",
      "values" : ["2"],
      "queryOption" : "equal"
    }
  ],
  "conditionOption" : "and"
}

### PUT BAR
PUT http://{{host}}:{{port}}/api/v1/bar/4
Content-Type: application/json

{
  "no": "4",
  "lyrics": "모습 생각",
  "fingeringId": "5",
  "sheetId": "2"
}

### DELETE BAR
DELETE http://{{host}}:{{port}}/api/v1/bar/6

### POST FINGERING
POST http://{{host}}:{{port}}/api/v1/fingering
Content-Type: application/json

{
  "type" : "guitar",
  "chord" : "Em",
  "notes" : [
    {
      "line" : "5",
      "space" : "2"
    },
    {
      "line" : "3",
      "space" : "7"
    }
  ]
}

### GET FINGERING
GET http://{{host}}:{{port}}/api/v1/fingering/2

### GET FINGERING LIST
GET http://{{host}}:{{port}}/api/v1/fingering?page=0&size=10

### QUERY ALL FINGERING
POST http://{{host}}:{{port}}/api/v1/fingering/query?page=0&size=10
Content-Type: application/json

{
  "conditions" : [
    {
      "target" : "type",
      "values" : ["gui", "pi"],
      "queryOption" : "like"
    }
  ],
  "conditionOption" : "or"
}

### PUT FINGERING
PUT http://{{host}}:{{port}}/api/v1/fingering/6
Content-Type: application/json

{
  "type" : "guitar",
  "chord" : "Am"
}

### DELETE FINGERING
DELETE http://{{host}}:{{port}}/api/v1/fingering/2

### POST NOTE
POST http://{{host}}:{{port}}/api/v1/note
Content-Type: application/json

{
  "line" : "8",
  "space" : "4",
  "fingeringId" : "6"
}

### GET NOTE
GET http://{{host}}:{{port}}/api/v1/note/2

### GET NOTE LIST
GET http://{{host}}:{{port}}/api/v1/note?page=0&size=10

### QUERY ALL NOTE
POST http://{{host}}:{{port}}/api/v1/note/query?page=0&size=10
Content-Type: application/json

{
  "conditions" : [
    {
      "target" : "name",
      "values" : ["별보러", "가자"],
      "queryOption" : "like"
    }
  ],
  "conditionOption" : "or"
}

### PUT NOTE
PUT http://{{host}}:{{port}}/api/v1/note/2
Content-Type: application/json

{
  "line" : "3",
  "space" : "4",
  "fingeringId" : "6"
}

### DELETE NOTE
DELETE http://{{host}}:{{port}}/api/v1/note/2

### POST MEMBER
POST http://{{host}}:{{port}}/api/v1/member
Content-Type: application/json

{
  "email" : "hello@world.com",
  "password" : "123456789"
}

### GET MEMBER
GET http://{{host}}:{{port}}/api/v1/member/hello@world.com

### GET MEMBER LIST
GET http://{{host}}:{{port}}/api/v1/member?page=0&size=10

### PUT MEMBER
PUT http://{{host}}:{{port}}/api/v1/member
Content-Type: application/json

{
  "email" : "hello@world.com",
  "password" : "abcdefghijk"
}

### DELETE MEMBER
DELETE http://{{host}}:{{port}}/api/v1/member/hello@world.com

### SEARCH LYRICS
GET http://{{host}}:{{port}}/api/v1/lyrics/search/a+thousand+years