### POST SHEET
POST http://{{host}}:{{gateway-port}}/api/v1/sheet
Content-Type: application/json

{
  "name" : "rain drop",
  "author" : "iu",
  "creatorEmail" : "s2mos2@naver.com"
}

### GET SHEET
GET http://{{host}}:{{gateway-port}}/api/v1/sheet/2

### GET SHEET LIST
GET http://{{host}}:{{gateway-port}}/api/v1/sheet?page=0&size=10

### QUERY ALL SHEET
POST http://{{host}}:{{gateway-port}}/api/v1/sheet/query?page=0&size=10
Content-Type: application/json

{
  "conditions" : [
    {
      "target" : "name",
      "values" : ["별보러", "가자"],
      "queryOption" : "like"
    }
  ],
  "conditionOption" : "or"
}

### PUT SHEET
PUT http://{{host}}:{{gateway-port}}/api/v1/sheet/2
Content-Type: application/json

{
  "name" : "it is up to you",
  "author" : "yunhwadngdng",
  "creatorEmail" : "hello@google.com"
}

### DELETE SHEET
DELETE http://{{host}}:{{gateway-port}}/api/v1/sheet/2

### POST BAR
POST http://{{host}}:{{gateway-port}}/api/v1/bar
Content-Type: application/json

{
  "no" : "",
  "lyrics" : "",
  "fingeringId" : "1",
  "sheetId" : "6"
}

### GET BAR
GET http://{{host}}:{{gateway-port}}/api/v1/bar/2

### GET BAR LIST
GET http://{{host}}:{{gateway-port}}/api/v1/bar?page=0&size=10&order=id

### QUERY ALL BAR
POST http://{{host}}:{{gateway-port}}/api/v1/bar/query?page=0&size=10
Content-Type: application/json

{
  "conditions" : [
    {
      "target" : "sheetId",
      "values" : ["6"],
      "queryOption" : "equal"
    }
  ],
  "conditionOption" : "and"
}

### PUT BAR
PUT http://{{host}}:{{gateway-port}}/api/v1/bar/7
Content-Type: application/json

{
  "no" : "1",
  "lyrics" : "",
  "fingeringId" : "5",
  "sheetId" : "6"
}

### DELETE BAR
DELETE http://{{host}}:{{gateway-port}}/api/v1/bar/6

### POST FINGERING
POST http://{{host}}:{{gateway-port}}/api/v1/fingering
Content-Type: application/json

{
  "type" : "guitar",
  "chord" : "C"
}

### GET FINGERING
GET http://{{host}}:{{gateway-port}}/api/v1/fingering/2

### GET FINGERING LIST
GET http://{{host}}:{{gateway-port}}/api/v1/fingering?page=0&size=10

### QUERY ALL FINGERING
POST http://{{host}}:{{gateway-port}}/api/v1/fingering/query?page=0&size=10
Content-Type: application/json

{
  "conditions" : [
    {
      "target" : "type",
      "values" : ["gui", "pi"],
      "queryOption" : "like"
    }
  ],
  "conditionOption" : "or"
}

### PUT FINGERING
PUT http://{{host}}:{{gateway-port}}/api/v1/fingering/2
Content-Type: application/json

{
  "type" : "piano",
  "chord" : "2"
}

### DELETE FINGERING
DELETE http://{{host}}:{{gateway-port}}/api/v1/fingering/2

### POST NOTE
POST http://{{host}}:{{gateway-port}}/api/v1/note
Content-Type: application/json

{
  "line" : "1",
  "space" : "2",
  "fingeringId" : "3"
}

### GET NOTE
GET http://{{host}}:{{gateway-port}}/api/v1/note/2

### GET NOTE LIST
GET http://{{host}}:{{gateway-port}}/api/v1/note?page=0&size=10

### QUERY ALL NOTE
POST http://{{host}}:{{port}}/api/v1/note/query?page=0&size=10
Content-Type: application/json

{
  "conditions" : [
    {
      "target" : "name",
      "values" : ["별보러", "가자"],
      "queryOption" : "like"
    }
  ],
  "conditionOption" : "or"
}

### PUT NOTE
PUT http://{{host}}:{{gateway-port}}/api/v1/note/2
Content-Type: application/json

{
  "line" : "3",
  "space" : "4",
  "fingeringId" : "6"
}

### DELETE NOTE
DELETE http://{{host}}:{{gateway-port}}/api/v1/note/2

### POST MEMBER
POST http://{{host}}:{{gateway-port}}/api/v1/member
Content-Type: application/json

{
  "email" : "hello@world.com",
  "password" : "123456789"
}

### GET MEMBER
GET http://{{host}}:{{gateway-port}}/api/v1/member/hello@world.com

### GET MEMBER LIST
GET http://{{host}}:{{gateway-port}}/api/v1/member?page=0&size=10

### PUT MEMBER
PUT http://{{host}}:{{gateway-port}}/api/v1/member
Content-Type: application/json

{
  "email" : "hello@world.com",
  "password" : "abcdefghijk"
}

### DELETE MEMBER
DELETE http://{{host}}:{{gateway-port}}/api/v1/member/hello@world.com